services:
  ccdh-api:
    container_name: ccdh-api
    ports:
      - "7070:8000"
    env_file:
      - .env
#    depends_on:
#      ccdh-neo4j:
#        condition: service_healthy
  ccdh-neo4j:
    container_name: neo4j
    ports:
      - $NEO4J_BOLT_PORT:7687
    environment:
      NEO4J_AUTH: $NEO4J_USERNAME/$NEO4J_PASSWORD
    env_file:
      - .env
