services:
  ccdh-api:
    container_name: ccdh-api-test
    ports:
      - "6070:7000"
    env_file:
      - .test.env
#    depends_on:
#      ccdh-neo4j:
#        condition: service_healthy
#ERROR: for neo4j-test  Cannot start service ccdh-neo4j: driver failed programming external connectivity on endpoint neo4j-test (b90b41b52d18df13c6d2431fd0b1cd234de214290fd5cb6919a40972d3d92ac6): Bind for 0.0.0.0:7687 failed: port is already allocated
  ccdh-neo4j:
    container_name: neo4j-test
    ports:
#      - $NEO4J_BOLT_PORT:6687
      - 6687:6687
    environment:
      NEO4J_AUTH: $NEO4J_USERNAME/$NEO4J_PASSWORD
    env_file:
      - .test.env
